//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreetingServiceConsoleClient.GreetingServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GreetingRequest", Namespace="http://schemas.datacontract.org/2004/07/GreetingService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GreetingServiceConsoleClient.GreetingServiceReference.GreetingResponse))]
    public partial class GreetingRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string LanguageField;
        
        private string TimeOfDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string TimeOfDay {
            get {
                return this.TimeOfDayField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeOfDayField, value) != true)) {
                    this.TimeOfDayField = value;
                    this.RaisePropertyChanged("TimeOfDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Tone {
            get {
                return this.ToneField;
            }
            set {
                if ((object.ReferenceEquals(this.ToneField, value) != true)) {
                    this.ToneField = value;
                    this.RaisePropertyChanged("Tone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GreetingResponse", Namespace="http://schemas.datacontract.org/2004/07/GreetingService")]
    [System.SerializableAttribute()]
    public partial class GreetingResponse : GreetingServiceConsoleClient.GreetingServiceReference.GreetingRequest {
        
        private string GreetingField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Greeting {
            get {
                return this.GreetingField;
            }
            set {
                if ((object.ReferenceEquals(this.GreetingField, value) != true)) {
                    this.GreetingField = value;
                    this.RaisePropertyChanged("Greeting");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GreetingServiceReference.IGreetingService")]
    public interface IGreetingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGreetingService/Greet", ReplyAction="http://tempuri.org/IGreetingService/GreetResponse")]
        GreetingServiceConsoleClient.GreetingServiceReference.GreetingResponse Greet(GreetingServiceConsoleClient.GreetingServiceReference.GreetingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGreetingService/Greet", ReplyAction="http://tempuri.org/IGreetingService/GreetResponse")]
        System.Threading.Tasks.Task<GreetingServiceConsoleClient.GreetingServiceReference.GreetingResponse> GreetAsync(GreetingServiceConsoleClient.GreetingServiceReference.GreetingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGreetingService/GetAllTimesOfDay", ReplyAction="http://tempuri.org/IGreetingService/GetAllTimesOfDayResponse")]
        string[] GetAllTimesOfDay();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGreetingService/GetAllTimesOfDay", ReplyAction="http://tempuri.org/IGreetingService/GetAllTimesOfDayResponse")]
        System.Threading.Tasks.Task<string[]> GetAllTimesOfDayAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGreetingService/GetSupportedLanguages", ReplyAction="http://tempuri.org/IGreetingService/GetSupportedLanguagesResponse")]
        string[] GetSupportedLanguages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGreetingService/GetSupportedLanguages", ReplyAction="http://tempuri.org/IGreetingService/GetSupportedLanguagesResponse")]
        System.Threading.Tasks.Task<string[]> GetSupportedLanguagesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGreetingServiceChannel : GreetingServiceConsoleClient.GreetingServiceReference.IGreetingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GreetingServiceClient : System.ServiceModel.ClientBase<GreetingServiceConsoleClient.GreetingServiceReference.IGreetingService>, GreetingServiceConsoleClient.GreetingServiceReference.IGreetingService {
        
        public GreetingServiceClient() {
        }
        
        public GreetingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GreetingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GreetingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GreetingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GreetingServiceConsoleClient.GreetingServiceReference.GreetingResponse Greet(GreetingServiceConsoleClient.GreetingServiceReference.GreetingRequest request) {
            return base.Channel.Greet(request);
        }
        
        public System.Threading.Tasks.Task<GreetingServiceConsoleClient.GreetingServiceReference.GreetingResponse> GreetAsync(GreetingServiceConsoleClient.GreetingServiceReference.GreetingRequest request) {
            return base.Channel.GreetAsync(request);
        }
        
        public string[] GetAllTimesOfDay() {
            return base.Channel.GetAllTimesOfDay();
        }
        
        public System.Threading.Tasks.Task<string[]> GetAllTimesOfDayAsync() {
            return base.Channel.GetAllTimesOfDayAsync();
        }
        
        public string[] GetSupportedLanguages() {
            return base.Channel.GetSupportedLanguages();
        }
        
        public System.Threading.Tasks.Task<string[]> GetSupportedLanguagesAsync() {
            return base.Channel.GetSupportedLanguagesAsync();
        }
    }
}
